name: main

on:
  push:
    branches:
      - list

jobs:
  run-script:
    name: job0
    runs-on: ubuntu-latest
    env: 
      TOKEN: ${{ secrets.TOKEN }}
      PASSWORD: ${{ secrets.PASSWORD }}
      PASSWORD_RCLONE: ${{ secrets.PASSWORD_RCLONE }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
    - run: pip install webdavclient3==3.14.5 rclone
    - run: sed -i "s|PASSWORD_RCLONE|$PASSWORD_RCLONE|" rclone.conf
    - run: mkdir -p /root/.config/rclone && mv rclone.conf /root/.config/rclone
    
    - run: bash get_json.sh
    - run: python3 main.py
    - run: ls data
    - run: rclone copy data/ webdav:data/
    - run: bash upload_nju.sh