name: main
on: workflow_dispatch

jobs:
  run-script:
    name: job0
    runs-on: ubuntu-latest
    env: 
      PASSWORD_RCLONE: ${{ secrets.PASSWORD_RCLONE }}
      GITLAB_TOKEN: ${{ secrets.GITLAB }}
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt update
    - run: sudo apt install -y rclone
    - run: sed -i "s|PASSWORD_RCLONE|$PASSWORD_RCLONE|" rclone.conf
    - run: mkdir -p ~/.config/rclone && mv rclone.conf ~/.config/rclone
    
    - run: bash main.sh
