name: main

on:
  push:
    branches:
      - list

jobs:
  run-script:
    name: job0
    runs-on: ubuntu-latest
    env: 
      PASSWORD: ${{ secrets.PASSWORD }}
      TOKEN: ${{ secrets.TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
    - run: pip install webdavclient3==3.14.5
    
    - run: bash get_json.sh
    - run: python3 main.py
    - run: bash upload_nju.sh