name: main

on:
  push:
    branches:
      - list

jobs:
  run-script:
    name: job0
    runs-on: ubuntu-latest
    env: 
      TOKEN: ${{ secrets.TOKEN }}
      PASSWORD: ${{ secrets.PASSWORD }}
      PASSWORD_RCLONE: ${{ secrets.PASSWORD_RCLONE }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
    - run: sudo apt update
    - run: sudo apt install -y rclone python3-requests
    - run: sed -i "s|PASSWORD_RCLONE|$PASSWORD_RCLONE|" rclone.conf
    - run: mkdir -p ~/.config/rclone && mv rclone.conf ~/.config/rclone
    
    - run: bash get_json.sh
    - run: python main.py
    - run: ls data
    - run: rclone copy data/ webdav:data/
    - run: bash upload_nju.sh