name: schedule

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches:
      - main
      - list

jobs:
  run-script:
    name: job0
    runs-on: ubuntu-latest
    env: 
      PASSWORD: ${{ secrets.PASSWORD }}
      TOKEN: ${{ secrets.TOKEN }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v3
    - run: pip install webdavclient3==3.14.5
    - run: bash get_data_list.sh
    - run: mkdir upload
    - run: python main.py
    - run: bash upload.sh
